### ISSUE TITLE
Cannot Open Installation Details When VSCode Light Theme is Active (Eclipse Crashes)

### ISSUE THREAD

**Issue by ingomohr** [gayanper/eclipse-themes#59]
Hi @gayanper!

Here's another one.
Actually, I found this when I wanted to retrieve the actual version for the other bug I created. ;)

Expected Scenario:
```
When user opens "Installation Details" via Help -> About Eclipse IDE
Then dialog listing all installed features appears
```
Actual: Dialog cannot be populated due to following SWT Error:

```
java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:498)
	at org.eclipse.e4.ui.workbench.renderers.swt.CTabRendering.createShadow(CTabRendering.java:901)
	at org.eclipse.e4.ui.workbench.renderers.swt.CTabRendering.drawShadow(CTabRendering.java:844)
	at org.eclipse.e4.ui.workbench.renderers.swt.CTabRendering.drawTabBody(CTabRendering.java:424)
	at org.eclipse.e4.ui.workbench.renderers.swt.CTabRendering.createShadow(CTabRendering.java:907)
	at org.eclipse.e4.ui.workbench.renderers.swt.CTabRendering.drawShadow(CTabRendering.java:844)
```

When I turn off the VS Code Light Theme again, the usecase works as expected.

**Comment by gayanper** [comment]
@ingomohr please try the latest version and select the "VSCode Light (Pre 2022-06)" theme.

**Comment by ingomohr** [comment]
@gayanper Thanks for the quick answer. I'll check the build tomorrow.

**Comment by ingomohr** [comment]
@gayanper Do you have an updatesite URL? I can find 3.0.0.202206011924 on https://gayanper.github.io/eclipse-themes/p2/i-builds/, but that's all.
And does that work only on Eclipse 2022-06 RC (if so, which RC - or which build is required?)
